[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

# API route rewrites
[[redirects]]
  from = "/api/bounties"
  to = "/.netlify/functions/bounties"
  status = 200

[[redirects]]
  from = "/api/tokens"
  to = "/.netlify/functions/tokens"
  status = 200

[[redirects]]
  from = "/api/token/*"
  to = "/.netlify/functions/token/:splat"
  status = 200

[[redirects]]
  from = "https://mint-index.netlify.app/*"
  to = "https://nodeworks.art/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://networkednodes.art/*"
  to = "https://nodeworks.art/:splat"
  status = 301
  force = true
